### ISSUE TITLE
Any ideas how to enforce Silhouette to cut even slower than speed=1 ?

### ISSUE THREAD

**Issue by petervojtek** [nosliwneb/robocut#6]
Hi robocut developers,
i want to thank you for your effort, robocut is really helpful piece of software.

I am actually using robocut+silhouette portrait for [laser burning](https://petervojtek.github.io/diy/2015/02/22/burning-map-on-plywood-with-silhouette-cutter.html) and my issue is that I would like to persuade the cutting head to move even slower than is the slowest speed=1 (from the range of speeds 1..10), so that the line burned by laser is thicker/more visible.

I inspected the [source code - Plotter.cpp](https://github.com/nosliwneb/robocut/blob/master/Plotter.cpp#L387) and it seems the physical speed is matter of firmware and thus there is no way to alter it in Robocut source code. 
Actually for curiosity I tried to enforce 
`speed = 0; e = UsbSend(handle, "!" + ItoS(speed) + "\x03");`
but the firmware seem to use speed=1 in such case.

So far I came up with following ideas:
- I inspected [Silhouette Cameo firmware](http://www.silhouetteamerica.com/firmware) but it does not seem to be easy to reverse engineer the firmware (and I actually own silhouette Portrait)
- I was wondering what would happen if I try to lower the voltage provided to the stepper motors (I have not disassembled the SIlhouette so I only guess there are stepper motors inside).
- it seems the [document size is passed via usb](https://github.com/nosliwneb/robocut/blob/master/Plotter.cpp#L434) and I thought on somehow cheating the Silhouette to believe the document is e.g., A6, but actually provide coordinates for A4 to make the movement 2x slower due to fake dimensions.

Any help is appreciated.

**Comment by nosliwneb** [comment]
You're welcome, though I can't take any credit. :) I actually forked this project because I needed to add compatibility for my Portrait and it didn't seem to be maintained elsewhere.

A couple suggestions:
- Instead of cutting once, cut twice
- Check out https://github.com/pmonta/gerber2graphtec. I can't confirm that it will go any slower, but it does seem optimized for more precise use cases
- I haven't opened mine either, but you're likely right that it uses steppers. If it is indeed a stepper, lowering the voltage won't have the desired effect.  Steppers work on a pulse train, so lowering the voltage would either result in garbage input to the motor driver, or possibly missed steps at higher speed, depending on where you lowered the voltage. However, theoretically you could install a multiplier/divider between the controller and get the effect you want, thought you'd need to be able to design circuits to do that :)

**Comment by petervojtek** [comment]
thank you for feedback.
just for completeness, to traverse the path twice does not seem to help as that much as I expected (I already tried it) - my guess is to burn a thicker line, the laser must spend more time heating a particular point on line. when the path is traversed twice, the critical temperature is not achieved.

**Comment by nosliwneb** [comment]
Oh, a couple other thoughts...
- if you haven't tried it already, you might try moving the laser focal
  point away from the surface. This probably won't improve the darkness of
  the line, but should make it wider.
- coating the surface with something that reacts better to the
  wavelength of your laser could also help
