### ISSUE TITLE
cutting to scale on cameo1

### ISSUE THREAD

**Issue by alexpseletr** [nosliwneb/robocut#8]
[desenhando.svg.zip](https://github.com/nosliwneb/robocut/files/1869249/desenhando.svg.zip)

I had the file attached, and I had it cut using an A4 sheet and when I went to see the result there were several small letters on the sheet (the whole page resulted in 65mm x 50mm) is the first time I used the application of voices, I used inkscape to to generate the file in archlinux x64

**Comment by nosliwneb** [comment]
Are you saying the scale was wrong?

I'm not sure how much help I can be since I haven't used this program myself in over 5 years and I didn't write it. If it's just a scaling issue you could try scaling up your inkscape file if you don't want to debug it more.

I did see that someone recently forked it. If I can't, maybe that person can?

**Comment by alexpseletr** [comment]
solved
in mainwindow.cpp line 148
mediaSize = rend.viewBoxF().size() * 25.4 / 96.0;
to
mediaSize = rend.viewBoxF().size() * 25.4 *3.7795275590551 / 96.0;
